server:
  ssl:
    enabled: false
logging:
  level: debug
portal:
  urlWhiteList: https://testcommunity.arachnenetwork.com:443
  useQueryInterceptor: true
achilles:
  executor:
    corePoolSize: 2
    maxPoolSize: 4
    queueCapacity: 100
