# suppress inspection "SpringBootApplicationProperties" for whole file
server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: odysseus
    key-password: odysseus
    keyAlias: arachne
    enabled-protocols: TLSv1.2
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
logging:
  level: info
spring:
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        connection:
          CharSet: utf8
          characterEncoding: utf8
          useUnicode: true
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5434/arachne_portal
    username: ohdsi
    password: ENC(0Lpfvg9UPAyaaZpSIqwaDg==)
    driver-class-name: org.postgresql.Driver
    max-active: 400
    connection-test-query: select 1
  cache:
    jcache:
      config: classpath:ehcache.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: odysseusinc.notifier
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  mvc:
    view:
      prefix: /
      suffix: .html
    throw-exception-if-no-handler-found: true
  thymeleaf:
    enabled: false
  http:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  resources:
    add-mappings: false
  activemq:
    broker-url: vm://localhost?broker.persistent=true
    packages:
      trust-all: true
build:
  number: @build.number@
  id: @build.id@
flyway:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  baseline-on-migrate: true
  placeholderReplacement: false
  out-of-order: true
  validateOnMigrate: false
  #locations: db/migration,classpath:com.odysseusinc.arachne.portal.db.migration
arachne:
  token:
    secret: sssshhhh!
    header: Arachne-Auth-Token
    expiration: 900
  systemToken:
    header: Arachne-System-Token
  resetPasswordToken:
    expiresMinutes: 60
  loginAttempts:
    count: 3
    resetMinutes: 3
  passwordBlacklist: password,secret,arachne
  solrServerUrl: http://localhost:8983/solr
  solrBatchSize: 90
  mail:
    notifier: odysseusinc.notifier@gmail.com
    signature: Regards,<br/> Odysseus Data Services, Inc.
    app-title: Arachne
swagger:
 enable: true

project:
  version: @project.version@

files:
  store:
    path: /var/arachne/files
    jcr-path: /var/arachne/files/jcr
  stdout:
    name: stdout.txt

analisis:
  file:
    maxsize: 1048576
user:
  enabled:
    default: true

# Available methods:
# NATIVE
portal:
  authMethod: NATIVE
  urlWhiteList: https://community.arachnenetwork.com:443
  useQueryInterceptor: false
  organizations:
    enableCreateByNonAdmin: true
  notifyAdminAboutNewUser: true
datanode:
  messaging:
    importTimeout: 60000
jasypt:
  encryptor:
    password:
achilles:
  executor:
    corePoolSize: 4
    maxPoolSize: 8
    queueCapacity: 200
#logging.level.org.hibernate.SQL=DEBUG
jodconverter:
  enabled: true
antivirus:
  host: localhost
  port: 3310
  retry:
    max-attempts: 10
    backoff:
      max-interval: 50000
tmp:
  holder:
    cron: 0 0 6 * * ?